# Generated by Django 2.1.2 on 2018-10-02 10:46

from datetime import timedelta

from django.db import migrations
from django.utils import timezone
from oauthlib.common import generate_token


def create_coursera_application(apps, schema_editor):
    Application = apps.get_model("oauth2_provider", "Application")
    AccessToken = apps.get_model("oauth2_provider", "AccessToken")

    application, created = Application.objects.update_or_create(
        name="Coursera API",
        defaults=dict(
            client_type="confidential",
            authorization_grant_type="client-credentials",
            skip_authorization=True,
        ),
    )
    if created:
        access_token = AccessToken.objects.create(
            application=application,
            token=generate_token(),
            scope="read write introspection",
            expires=timezone.now() + timedelta(days=5 * 365),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20180925_1005"),
        ("oauth2_provider", "0006_auto_20171214_2232"),
    ]

    operations = [migrations.RunPython(create_coursera_application)]
