language: python
python:
  - "3.6"

services:
  - postgresql

install:
  - pip install pipenv
  - pipenv sync --dev

before_script:
  - psql -c 'create database test_db;' -U postgres
script:
  - pytest --cov
