language: python
python:
  - "3.6"

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

services:
  - postgresql

cache:
  directories:
    - $HOME/.cache/pip/
    - $HOME/.cache/pipenv/
    - $HOME/.cache/db/

install:
  - pip install pipenv
  - pipenv sync --dev

before_script:
  - git clone git@github.com:cornytrace/SEP-Autumn-2018-Group2-Backend.git --branch coursera_db --single-branch $HOME/.cache/db/
  - pg_restore -U postgres -O -C $HOME/.cache/db/coursera
script:
  - pytest --cov
