language: python
python:
  - "3.6"

addons:
  postgresql: "9.6"

services:
  - postgresql

cache:
  directories:
    - $HOME/.cache/pip/
    - $HOME/.cache/pipenv/

install:
  - pip install pipenv
  - pipenv sync --dev

before_script:
  - psql -c 'create database test_db;' -U postgres
script:
  - pytest --cov

before_deploy:
  - pip install ansible
  - git clone https://knbk:$GITHUB_TOKEN@github.com/knbk/ansible-dashit.git
  - cd ansible-dashit/

deploy:
  provider: script
  script: ansible-playbook deploy.yml
  on:
    branch: master
