# Generated by Django 2.1.2 on 2018-10-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180918_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registered_actions', to='courses.Course', to_field='course_id')),
            ],
        ),
    ]
